vault-injector: Supports only admissions of v1beta1
evry-ace/helm-charts pull request #124
Opened 2021-04-05 18:19 UTC by ekarlso

2021-04-06 14:21 UTC, ah9828 requested changes
sjekk også i linje 7 på java/templates/NOTES.txt

2021-04-06 14:21 UTC, ah9828 commented on dotnet/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "java.name" . }})
```suggestion
  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "libchart.name" . }})
```

2021-04-06 14:21 UTC, ah9828 commented on golang/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "java.name" . }})
```suggestion
  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "libchart.name" . }})
```

2021-04-06 14:21 UTC, ah9828 commented on nodejs/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "java.name" . }})
```suggestion
  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "libchart.name" . }})
```

2021-04-06 14:21 UTC, ah9828 commented on web/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "java.name" . }})
```suggestion
  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "libchart.name" . }})
```

2021-04-07 12:31 UTC, Haavare commented
When the comments are resolved this looks good

2021-04-08 08:13 UTC, ah9828 requested changes
@ekarlso Etter å ha sjekket nøyere etter så lurer jeg på om du generer duplikater siden du både har templates mappen for hvert språk og har tillegg templates mappen med samme tingene i libchart

2021-04-13 18:42 UTC, Haavare commented
I can't se any duplicated `*.yaml` files, the `_*.tpl` files will not create files of their own.

2021-04-13 18:44 UTC, Haavare commented
@ekarlso you have to run `helm dependency update` to import the libchart tar file into `/charts`

2021-04-13 18:48 UTC, Haavare commented
here is a example of `helm template libchart-test ./dotnet/` after importing the libchar  tar file:
```
---
# Source: dotnet/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: libchart-test-dotnet
  namespace: marine-resources-prod
  labels:
    helm.sh/chart: dotnet-9.0.0

    app.kubernetes.io/name: libchart-test
    app.kubernetes.io/instance: libchart-test

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: libchart-test
    app.kubernetes.io/component: libchart-test
---
# Source: dotnet/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: libchart-test
  namespace: marine-resources-prod
  labels:
    helm.sh/chart: dotnet-9.0.0

    app.kubernetes.io/name: libchart-test
    app.kubernetes.io/instance: libchart-test

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: libchart-test
    app.kubernetes.io/component: libchart-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

  selector:

    app.kubernetes.io/name: libchart-test
    app.kubernetes.io/instance: libchart-test
---
# Source: dotnet/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libchart-test
  namespace: marine-resources-prod
  labels:
    helm.sh/chart: dotnet-9.0.0

    app.kubernetes.io/name: libchart-test
    app.kubernetes.io/instance: libchart-test

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: libchart-test
    app.kubernetes.io/component: libchart-test
spec:
  replicas: 1
  selector:
    matchLabels:

      app.kubernetes.io/name: libchart-test
      app.kubernetes.io/instance: libchart-test
  template:
    metadata:
      labels:
        helm.sh/chart: dotnet-9.0.0

        app.kubernetes.io/name: libchart-test
        app.kubernetes.io/instance: libchart-test

        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: libchart-test
        app.kubernetes.io/component: libchart-test
    spec:

      serviceAccountName: libchart-test-dotnet
      securityContext:
        runAsNonRoot: true
      containers:
        - name: dotnet
          image: ":"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 15
          env:
          resources:

            {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:

                    app.kubernetes.io/name: libchart-test
                    app.kubernetes.io/instance: libchart-test
---
# Source: dotnet/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: libchart-test
  namespace: marine-resources-prod
  labels:
    helm.sh/chart: dotnet-9.0.0

    app.kubernetes.io/name: libchart-test
    app.kubernetes.io/instance: libchart-test

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: libchart-test
    app.kubernetes.io/component: libchart-test
    prometheus: default
spec:
  selector:
    matchLabels:

      app.kubernetes.io/name: libchart-test
      app.kubernetes.io/instance: libchart-test
  endpoints:
  - path: /metrics
    interval: 15s
    targetPort: 8080
    honorLabels: true
```
I do not know if this is a good example

2021-04-13 18:57 UTC, Haavare commented
I think this is a good examle of a situation where Architecture Decision Records would make sense to have:
https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions

At the moment I am not sure why libchart is considered less complex than maintaining separate charts

2021-04-15 14:30 UTC, ekarlso commented
> I think this is a good examle of a situation where Architecture Decision Records would make sense to have:
> https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions
> 
> At the moment I am not sure why libchart is considered less complex than maintaining separate charts

Because now implementing a change or a common component is at least common across them all ;)

Whether we should actually have seperate charts for java, dotnet, or whatever language you think if is a better valid question in my mind.

2021-04-15 15:55 UTC, Haavare commented
Yes, I actually thought you all decided only the `web` chart was necessary two years ago

2021-04-15 19:56 UTC, Haavare commented
There are `namespace` in some but not all templates, I do not think we need them, but could we be consistent either or.

2021-04-18 14:27 UTC, ekarlso commented
> There are `namespace` in some but not all templates, I do not think we need them, but could we be consistent either or.

Removed namespaces and now and added policy to keep it removed :

2021-04-20 18:39 UTC, Haavare reviewed
You check if it is a statefulset twice, on include and define. I think that is fine.
I am not familiar with the Istio templates, so I just checke spelling.
Otherwise did you see my comment on labelSelectors above? That is the only thing I have left

2021-04-20 18:39 UTC, Haavare commented on web/values.yaml
> +  # secretName: java-appname-tls
It is not that important but you have this java comment in all the charts

2021-04-21 19:41 UTC, ekarlso commented on .gitmodules
> +       url = https://github.com/evry-ace/helm-istio-bookinfo.git
Done automatically I believe :thinking:

2021-04-21 19:43 UTC, ekarlso commented on libchart/templates/_helpers.tpl
> +{{ include "libchart.versionLabel" . }}
:+1:

2021-04-21 19:43 UTC, ekarlso commented on golang/templates/cm-certificate.yaml
> -apiVersion: {{ .Values.certmanagerApiVersion }}
Yes, breaking change because cert-manager v1 is introduced long long time ago. Also there's a better way to do apiVersion detection atm.

2021-04-21 19:44 UTC, ekarlso commented on dotnet/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "java.name" . }})
This is already done.

2021-04-21 19:44 UTC, ekarlso commented
> You check if it is a statefulset twice, on include and define. I think that is fine.
> I am not familiar with the Istio templates, so I just checke spelling.
> Otherwise did you see my comment on labelSelectors? That is the only thing I have left, great work!

Where's this?

2021-04-22 07:13 UTC, ah9828 commented
Good work @ekarlso!

2021-04-22 09:52 UTC, Haavare commented
> > You check if it is a statefulset twice, on include and define. I think that is fine.
> > I am not familiar with the Istio templates, so I just checke spelling.
> > Otherwise did you see my comment on labelSelectors? That is the only thing I have left, great work!
> 
> Where's this?

Looks like you have changed it, all good

2021-04-22 09:53 UTC, Haavare approved these changes

2021-04-22 15:41 UTC, ah9828 approved these changes

2021-04-23 06:12 UTC, merged